FROM ubuntu:14.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -y --no-install-recommends software-properties-common && add-apt-repository -y ppa:webupd8team/java && \
    apt-get update && \
    (echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections) && \
    apt-get install --no-install-recommends -y oracle-java8-installer && \
    rm -rf /var/cache/oracle-jdk8-installer && \
    echo "networkaddress.cache.ttl=60" >> /usr/lib/jvm/java-8-oracle/jre/lib/security/java.security && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
ENV JAVA_HOME /usr/lib/jvm/java-8-oracle
RUN groupadd -g 1000 elasticsearch && useradd elasticsearch -u 1000 -g 1000

RUN apt-key adv --keyserver pgp.mit.edu --recv-keys 46095ACC8548582C1A2699A9D27D666CD88E42B4 && \
    add-apt-repository -y "deb http://packages.elastic.co/elasticsearch/2.x/debian stable main" --keyserver https://pgp.mit.edu/ && \
    apt-get update && \
    apt-get install -y --no-install-recommends elasticsearch

WORKDIR /usr/share/elasticsearch

RUN set -ex && for path in data logs config config/scripts; do \
        mkdir -p "$path"; \
        chown -R elasticsearch:elasticsearch "$path"; \
    done

RUN apt-get update && apt-get install -y ca-certificates wget

RUN wget https://download.elasticsearch.org/kibana/kibana/kibana-4.0.1-linux-x64.tar.gz -O /tmp/kibana.tar.gz 2> /dev/null

RUN tar zxvf /tmp/kibana.tar.gz -C /tmp && mv /tmp/kibana-4.0.1-linux-x64 /kibana && rm -rf /tmp/*

RUN mkdir /logs

#ADD start_kibana.sh /usr/local/bin/start_kibana.sh
#RUN chmod +x /usr/local/bin/start_kibana.sh

#VOLUME ["/kibana/config", "/logs"]

#CMD ["/usr/local/bin/start_kibana.sh"]

USER root
ENV PATH=$PATH:/usr/share/elasticsearch/bin
COPY logging.yml /usr/share/elasticsearch/config/
COPY elasticsearch.yml /usr/share/elasticsearch/config/
COPY start.sh /usr/share/elasticsearch/bin
RUN chown elasticsearch:elasticsearch /usr/share/elasticsearch/bin/start.sh
RUN chmod 755 /usr/share/elasticsearch/bin/start.sh
RUN mkdir /home/elasticsearch
RUN chown elasticsearch:elasticsearch /home/elasticsearch
RUN chown -R elasticsearch:elasticsearch /kibana
RUN chown -R elasticsearch:elasticsearch /logs
USER elasticsearch

CMD bash -C '/usr/share/elasticsearch/bin/start.sh'

EXPOSE 9200 9300
